[package]
name = "grust"
version = "0.1.0"
authors = ["Yomain <arnal.romain@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
colored = "1.9"
